image: php:7.4

services:
    - redis:latest
    - memcached:latest

stages:
    - test

test:
    stage: test
    coverage: /^\s*Lines:\s*\d+.\d+\%/
    before_script:
        - bash ci/docker_install.sh > /dev/null
    script:
        - php vendor/bin/phpunit --configuration phpunit.docker.xml
    only:
        - release
        - merge_requests
        - tags