name: Tests, Security and Psalm

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
      memcached:
        image: memcached
        ports:
          - 11211:11211

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: php vendor/bin/phpunit
      env:
        REDIS_HOST: redis
        MEMCACHED_HOST: memcached

    - name: Security Checker
      uses: StephaneBour/actions-php-security-checker@1.0

    - name: Psalm
      uses: mickaelandrieu/psalm-ga@v1.1
