name: Tests, Security and Psalm

on:
    push_requests:
        branches: [ releases ]

jobs:
    build:
        runs-on: ubuntu-latest

        services:
            redis:
                image: redis
                ports:
                    - 6379:6379
                options: >-
                    --health-cmd "redis-cli ping"
                    --health-interval 10s
                    --health-timeout 5s
                    --health-retries 5

        steps:
            - uses: actions/checkout@v2

            - name: Validate composer.json and composer.lock
              run: composer validate

            - name: Install dependencies
              run: composer install --prefer-dist --no-progress --no-suggest

            - name: Run test suite
              run: php vendor/bin/phpunit
              env:

                  REDIS_HOST: localhost
                  REDIS_PORT: 6379
                  MEMCACHED_HOST: localhost
                  MEMCACHED_PORT: 11211
