name: PHP Composer

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
      memcached:
        image: memcached

    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Run test suite
      run: php vendor/bin/phpunit --configuration phpunit.docker.xml

    - name: PHP Security Checker
      uses: StephaneBour/actions-php-security-checker@1.0

    - name: Psalm - Code quality tool for PHP
      uses: mickaelandrieu/psalm-ga@v1.1
